runtime: custom
env: flex
resources:
  cpu: 8
  memory_gb: 32
  disk_size_gb: 60
network:
  name: default
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 10
  success_threshold: 1
  initial_delay_sec: 3600
readiness_check:
  path: "/readiness_check"
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 10
  success_threshold: 1
  app_start_timeout_sec: 1800
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100

